<?php

declare(strict_types=1);

return [
    'profile' => '__PROFILE__',
    'paths' => [
        'content_root' => '__CONTENT_ROOT__',
        'plugins_root' => '__PLUGINS_ROOT__',
        'themes_root' => '__THEMES_ROOT__',
        'mu_plugins_root' => '__MU_PLUGINS_ROOT__',
    ],
    'core' => [
        'mode' => '__CORE_MODE__',
        'enabled' => __CORE_ENABLED__,
    ],
    'runtime' => [
        'stage_dir' => '.wp-core-base/build/runtime',
        'manifest_mode' => '__MANIFEST_MODE__',
        'validation_mode' => '__VALIDATION_MODE__',
        'ownership_roots' => __OWNERSHIP_ROOTS__,
        'staged_kinds' => __STAGED_KINDS__,
        'validated_kinds' => __VALIDATED_KINDS__,
        'forbidden_paths' => [
            '.git',
            '.github',
            '.gitlab',
            '.gitea',
            '.forgejo',
            '.circleci',
            '.wordpress-org',
            'node_modules',
            'docs',
            'doc',
            'tests',
            'test',
            '__tests__',
            'examples',
            'example',
            'demo',
            'screenshots',
        ],
        'forbidden_files' => [
            'README*',
            'CHANGELOG*',
            '.gitignore',
            '.gitattributes',
            '.gitlab-ci.yml',
            'bitbucket-pipelines.yml',
            'phpunit.xml*',
            'composer.json',
            'composer.lock',
            'package.json',
            'package-lock.json',
            'pnpm-lock.yaml',
            'yarn.lock',
        ],
        'allow_runtime_paths' => [],
        'strip_paths' => [],
        'strip_files' => [],
        'managed_sanitize_paths' => __MANAGED_SANITIZE_PATHS__,
        'managed_sanitize_files' => __MANAGED_SANITIZE_FILES__,
    ],
    'github' => [
        'api_base' => getenv('GITHUB_API_URL') ?: 'https://api.github.com',
    ],
    'gitlab' => [
        'api_base' => getenv('CI_API_V4_URL') ?: 'https://gitlab.com/api/v4',
    ],
    'automation' => [
        'provider' => '__AUTOMATION_PROVIDER__',
        'api_base' => __AUTOMATION_API_BASE__,
        'base_branch' => null,
        'dry_run' => false,
        'managed_kinds' => __MANAGED_KINDS__,
    ],
    'dependencies' => [
        // content-only repos should declare every managed dependency explicitly.
        // local entries are first-class and are the normal way to keep project-owned code in the repo.
        // Example managed WordPress.org plugin:
        // [
        //     'name' => 'WooCommerce',
        //     'slug' => 'woocommerce',
        //     'kind' => 'plugin',
        //     'management' => 'managed',
        //     'source' => 'wordpress.org',
        //     'path' => '__PLUGINS_ROOT__/woocommerce',
        //     'main_file' => 'woocommerce.php',
        //     'version' => '10.6.1',
        //     'checksum' => 'sha256:...',
        //     'archive_subdir' => '',
        //     'extra_labels' => ['plugin:woocommerce'],
        //     'source_config' => [
        //         'github_repository' => null,
        //         'github_release_asset_pattern' => null,
        //         'github_token_env' => null,
        //     ],
        //     'policy' => [
        //         'class' => 'managed-upstream',
        //         'allow_runtime_paths' => [],
        //         'sanitize_paths' => [],
        //         'sanitize_files' => [],
        //     ],
        // ],
        // Example managed GitHub Release plugin:
        // [
        //     'name' => 'Example Private Plugin',
        //     'slug' => 'example-private-plugin',
        //     'kind' => 'plugin',
        //     'management' => 'managed',
        //     'source' => 'github-release',
        //     'path' => '__PLUGINS_ROOT__/example-private-plugin',
        //     'main_file' => 'example-private-plugin.php',
        //     'version' => '1.2.3',
        //     'checksum' => 'sha256:...',
        //     'archive_subdir' => '',
        //     'extra_labels' => ['plugin:example-private-plugin'],
        //     'source_config' => [
        //         'github_repository' => 'owner/private-plugin',
        //         'github_release_asset_pattern' => '*.zip',
        //         'github_token_env' => 'PRIVATE_PLUGIN_GITHUB_TOKEN',
        //     ],
        //     'policy' => [
        //         'class' => 'managed-private',
        //         'allow_runtime_paths' => [],
        //         'sanitize_paths' => [],
        //         'sanitize_files' => [],
        //     ],
        // ],
        // Example managed GitLab Release plugin:
        // [
        //     'name' => 'Example GitLab Plugin',
        //     'slug' => 'example-gitlab-plugin',
        //     'kind' => 'plugin',
        //     'management' => 'managed',
        //     'source' => 'gitlab-release',
        //     'path' => '__PLUGINS_ROOT__/example-gitlab-plugin',
        //     'main_file' => 'example-gitlab-plugin.php',
        //     'version' => '1.2.3',
        //     'checksum' => 'sha256:...',
        //     'archive_subdir' => '',
        //     'extra_labels' => ['plugin:example-gitlab-plugin'],
        //     'source_config' => [
        //         'gitlab_project' => 'group/example-gitlab-plugin',
        //         'gitlab_release_asset_pattern' => '*.zip',
        //         'gitlab_token_env' => 'EXAMPLE_GITLAB_PLUGIN_TOKEN',
        //     ],
        //     'policy' => [
        //         'class' => 'managed-private',
        //         'allow_runtime_paths' => [],
        //         'sanitize_paths' => [],
        //         'sanitize_files' => [],
        //     ],
        // ],
        // Example local project-owned theme:
        // [
        //     'name' => 'Project Theme',
        //     'slug' => 'project-theme',
        //     'kind' => 'theme',
        //     'management' => 'local',
        //     'source' => 'local',
        //     'path' => '__THEMES_ROOT__/project-theme',
        //     'main_file' => 'style.css',
        //     'version' => '1.0.0',
        //     'checksum' => null,
        //     'archive_subdir' => '',
        //     'extra_labels' => ['theme:project-theme'],
        //     'source_config' => [
        //         'github_repository' => null,
        //         'github_release_asset_pattern' => null,
        //         'github_token_env' => null,
        //     ],
        //     'policy' => [
        //         'class' => 'local-owned',
        //         'allow_runtime_paths' => [],
        //         'strip_paths' => [],
        //         'strip_files' => ['README*', 'package.json'],
        //     ],
        // ],
        // Example local single-file MU plugin:
        // [
        //     'name' => 'Project Bootstrap',
        //     'slug' => 'project-bootstrap-loader',
        //     'kind' => 'mu-plugin-file',
        //     'management' => 'local',
        //     'source' => 'local',
        //     'path' => '__MU_PLUGINS_ROOT__/project-bootstrap-loader.php',
        //     'version' => '1.0.0',
        //     'checksum' => null,
        //     'archive_subdir' => '',
        //     'extra_labels' => ['mu-plugin:project-bootstrap-loader'],
        //     'source_config' => [
        //         'github_repository' => null,
        //         'github_release_asset_pattern' => null,
        //         'github_token_env' => null,
        //     ],
        //     'policy' => [
        //         'class' => 'local-owned',
        //         'allow_runtime_paths' => [],
        //         'strip_paths' => [],
        //         'strip_files' => [],
        //     ],
        // ],
        // Example local runtime directory outside plugins/themes:
        // [
        //     'name' => 'Shared Assets',
        //     'slug' => 'shared-assets',
        //     'kind' => 'runtime-directory',
        //     'management' => 'local',
        //     'source' => 'local',
        //     'path' => '__CONTENT_ROOT__/shared-assets',
        //     'version' => null,
        //     'checksum' => null,
        //     'archive_subdir' => '',
        //     'extra_labels' => [],
        //     'source_config' => [
        //         'github_repository' => null,
        //         'github_release_asset_pattern' => null,
        //         'github_token_env' => null,
        //     ],
        //     'policy' => [
        //         'class' => 'local-owned',
        //         'allow_runtime_paths' => [],
        //         'strip_paths' => [],
        //         'strip_files' => [],
        //     ],
        // ],
    ],
];
