version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "peter-evans/create-pull-request"
    labels:
      - dependencies
      - github-actions
