<?php

declare(strict_types=1);

return [
    'profile' => 'content-only',
    'paths' => [
        'content_root' => 'cms',
        'plugins_root' => 'cms/plugins',
        'themes_root' => 'cms/themes',
        'mu_plugins_root' => 'cms/mu-plugins',
    ],
    'core' => [
        'mode' => 'external',
        'enabled' => false,
    ],
    'runtime' => [
        'stage_dir' => '.wp-core-base/build/runtime',
        'manifest_mode' => 'strict',
        'validation_mode' => 'source-clean',
        'ownership_roots' => ['cms/plugins', 'cms/themes', 'cms/mu-plugins', 'cms/shared-assets'],
        'staged_kinds' => ['plugin', 'theme', 'mu-plugin-package', 'mu-plugin-file', 'runtime-file', 'runtime-directory'],
        'validated_kinds' => ['plugin', 'theme', 'mu-plugin-package', 'mu-plugin-file', 'runtime-file', 'runtime-directory'],
        'forbidden_paths' => [
            '.git',
            '.github',
            '.gitlab',
            '.gitea',
            '.forgejo',
            '.circleci',
            '.wordpress-org',
            'node_modules',
            'docs',
            'doc',
            'tests',
            'test',
            '__tests__',
            'examples',
            'example',
            'demo',
            'screenshots',
        ],
        'forbidden_files' => [
            'README*',
            'CHANGELOG*',
            '.gitignore',
            '.gitattributes',
            '.gitlab-ci.yml',
            'bitbucket-pipelines.yml',
            'phpunit.xml*',
            'composer.json',
            'composer.lock',
            'package.json',
            'package-lock.json',
            'pnpm-lock.yaml',
            'yarn.lock',
        ],
        'allow_runtime_paths' => [],
        'strip_paths' => [],
        'strip_files' => [],
        'managed_sanitize_paths' => [
            'cms/plugins/.github',
            'cms/plugins/.gitlab',
            'cms/plugins/.gitea',
            'cms/plugins/.forgejo',
            'cms/plugins/.circleci',
            'cms/plugins/.wordpress-org',
            'cms/plugins/node_modules',
            'cms/plugins/docs',
            'cms/plugins/doc',
            'cms/plugins/tests',
            'cms/plugins/test',
            'cms/plugins/__tests__',
            'cms/plugins/examples',
            'cms/plugins/example',
            'cms/plugins/demo',
            'cms/plugins/screenshots',
            'cms/themes/.github',
            'cms/themes/.gitlab',
            'cms/themes/.gitea',
            'cms/themes/.forgejo',
            'cms/themes/.circleci',
            'cms/themes/.wordpress-org',
            'cms/themes/node_modules',
            'cms/themes/docs',
            'cms/themes/doc',
            'cms/themes/tests',
            'cms/themes/test',
            'cms/themes/__tests__',
            'cms/themes/examples',
            'cms/themes/example',
            'cms/themes/demo',
            'cms/themes/screenshots',
            'cms/mu-plugins/.github',
            'cms/mu-plugins/.gitlab',
            'cms/mu-plugins/.gitea',
            'cms/mu-plugins/.forgejo',
            'cms/mu-plugins/.circleci',
            'cms/mu-plugins/.wordpress-org',
            'cms/mu-plugins/node_modules',
            'cms/mu-plugins/docs',
            'cms/mu-plugins/doc',
            'cms/mu-plugins/tests',
            'cms/mu-plugins/test',
            'cms/mu-plugins/__tests__',
            'cms/mu-plugins/examples',
            'cms/mu-plugins/example',
            'cms/mu-plugins/demo',
            'cms/mu-plugins/screenshots',
        ],
        'managed_sanitize_files' => [
            'README*',
            'CHANGELOG*',
            '.gitignore',
            '.gitattributes',
            '.gitlab-ci.yml',
            'bitbucket-pipelines.yml',
            'phpunit.xml*',
            'composer.json',
            'composer.lock',
            'package.json',
            'package-lock.json',
            'pnpm-lock.yaml',
            'yarn.lock',
        ],
    ],
    'github' => [
        'api_base' => getenv('GITHUB_API_URL') ?: 'https://api.github.com',
    ],
    'gitlab' => [
        'api_base' => getenv('CI_API_V4_URL') ?: 'https://gitlab.com/api/v4',
    ],
    'automation' => [
        // This example keeps automation on GitHub. See downstream-manifest-gitlab.php for a GitLab-first setup.
        'provider' => 'github',
        'api_base' => getenv('GITHUB_API_URL') ?: 'https://api.github.com',
        'base_branch' => null,
        'dry_run' => (bool) getenv('WPORG_UPDATE_DRY_RUN'),
        'managed_kinds' => ['plugin', 'theme'],
    ],
    'dependencies' => [
        [
            'name' => 'WooCommerce',
            'slug' => 'woocommerce',
            'kind' => 'plugin',
            'management' => 'managed',
            'source' => 'wordpress.org',
            'path' => 'cms/plugins/woocommerce',
            'main_file' => 'woocommerce.php',
            'version' => '10.6.1',
            'checksum' => 'sha256:...',
            'archive_subdir' => '',
            'extra_labels' => ['plugin:woocommerce'],
            'source_config' => [
                'github_repository' => null,
                'github_release_asset_pattern' => null,
                'github_token_env' => null,
            ],
            'policy' => [
                'class' => 'managed-upstream',
                'allow_runtime_paths' => [],
                'sanitize_paths' => [],
                'sanitize_files' => [],
            ],
        ],
        [
            'name' => 'Example Private Plugin',
            'slug' => 'example-private-plugin',
            'kind' => 'plugin',
            'management' => 'managed',
            'source' => 'github-release',
            'path' => 'cms/plugins/example-private-plugin',
            'main_file' => 'example-private-plugin.php',
            'version' => '1.2.3',
            'checksum' => 'sha256:...',
            'archive_subdir' => '',
            'extra_labels' => ['plugin:example-private-plugin'],
            'source_config' => [
                'github_repository' => 'owner/private-plugin',
                'github_release_asset_pattern' => '*.zip',
                'github_token_env' => 'PRIVATE_PLUGIN_GITHUB_TOKEN',
                'gitlab_project' => null,
                'gitlab_release_asset_pattern' => null,
                'gitlab_token_env' => null,
                'gitlab_api_base' => null,
                'generic_json_url' => null,
            ],
            'policy' => [
                'class' => 'managed-private',
                'allow_runtime_paths' => [],
                'sanitize_paths' => [],
                'sanitize_files' => [],
            ],
        ],
        [
            // Dependency source is independent from the automation host.
            'name' => 'Example GitLab Plugin',
            'slug' => 'example-gitlab-plugin',
            'kind' => 'plugin',
            'management' => 'managed',
            'source' => 'gitlab-release',
            'path' => 'cms/plugins/example-gitlab-plugin',
            'main_file' => 'example-gitlab-plugin.php',
            'version' => '1.2.3',
            'checksum' => 'sha256:...',
            'archive_subdir' => '',
            'extra_labels' => ['plugin:example-gitlab-plugin'],
            'source_config' => [
                'github_repository' => null,
                'github_release_asset_pattern' => null,
                'github_token_env' => null,
                'gitlab_project' => 'group/example-gitlab-plugin',
                'gitlab_release_asset_pattern' => '*.zip',
                'gitlab_token_env' => 'EXAMPLE_GITLAB_PLUGIN_TOKEN',
                'gitlab_api_base' => null,
                'generic_json_url' => null,
            ],
            'policy' => [
                'class' => 'managed-private',
                'allow_runtime_paths' => [],
                'sanitize_paths' => [],
                'sanitize_files' => [],
            ],
        ],
        [
            'name' => 'Example JSON Plugin',
            'slug' => 'example-json-plugin',
            'kind' => 'plugin',
            'management' => 'managed',
            'source' => 'generic-json',
            'path' => 'cms/plugins/example-json-plugin',
            'main_file' => 'example-json-plugin.php',
            'version' => '1.2.3',
            'checksum' => 'sha256:...',
            'archive_subdir' => '',
            'extra_labels' => ['plugin:example-json-plugin'],
            'source_config' => [
                'github_repository' => null,
                'github_release_asset_pattern' => null,
                'github_token_env' => null,
                'gitlab_project' => null,
                'gitlab_release_asset_pattern' => null,
                'gitlab_token_env' => null,
                'gitlab_api_base' => null,
                'generic_json_url' => 'https://updates.example.com/example-json-plugin/info.json',
            ],
            'policy' => [
                'class' => 'managed-private',
                'allow_runtime_paths' => [],
                'sanitize_paths' => [],
                'sanitize_files' => [],
            ],
        ],
        [
            'name' => 'Project Theme',
            'slug' => 'project-theme',
            'kind' => 'theme',
            'management' => 'local',
            'source' => 'local',
            'path' => 'cms/themes/project-theme',
            'main_file' => 'style.css',
            'version' => '1.0.0',
            'checksum' => null,
            'archive_subdir' => '',
            'extra_labels' => ['theme:project-theme'],
            'source_config' => [
                'github_repository' => null,
                'github_release_asset_pattern' => null,
                'github_token_env' => null,
                'gitlab_project' => null,
                'gitlab_release_asset_pattern' => null,
                'gitlab_token_env' => null,
                'gitlab_api_base' => null,
            ],
            'policy' => [
                'class' => 'local-owned',
                'allow_runtime_paths' => [],
                'strip_paths' => [],
                'strip_files' => ['README*', 'package.json'],
            ],
        ],
        [
            'name' => 'Project Bootstrap',
            'slug' => 'project-bootstrap',
            'kind' => 'mu-plugin-file',
            'management' => 'local',
            'source' => 'local',
            'path' => 'cms/mu-plugins/project-bootstrap.php',
            'version' => '1.0.0',
            'checksum' => null,
            'archive_subdir' => '',
            'extra_labels' => ['mu-plugin:project-bootstrap'],
            'source_config' => [
                'github_repository' => null,
                'github_release_asset_pattern' => null,
                'github_token_env' => null,
                'gitlab_project' => null,
                'gitlab_release_asset_pattern' => null,
                'gitlab_token_env' => null,
                'gitlab_api_base' => null,
            ],
            'policy' => [
                'class' => 'local-owned',
                'allow_runtime_paths' => [],
                'strip_paths' => [],
                'strip_files' => [],
            ],
        ],
        [
            'name' => 'Shared Assets',
            'slug' => 'shared-assets',
            'kind' => 'runtime-directory',
            'management' => 'local',
            'source' => 'local',
            'path' => 'cms/shared-assets',
            'version' => null,
            'checksum' => null,
            'archive_subdir' => '',
            'extra_labels' => [],
            'source_config' => [
                'github_repository' => null,
                'github_release_asset_pattern' => null,
                'github_token_env' => null,
                'gitlab_project' => null,
                'gitlab_release_asset_pattern' => null,
                'gitlab_token_env' => null,
                'gitlab_api_base' => null,
            ],
            'policy' => [
                'class' => 'local-owned',
                'allow_runtime_paths' => [],
                'strip_paths' => [],
                'strip_files' => [],
            ],
        ],
    ],
];
