<?php

declare(strict_types=1);

return [
    'profile' => 'content-only',
    'paths' => [
        'content_root' => 'cms',
        'plugins_root' => 'cms/plugins',
        'themes_root' => 'cms/themes',
        'mu_plugins_root' => 'cms/mu-plugins',
    ],
    'core' => [
        'mode' => 'external',
        'enabled' => false,
    ],
    'runtime' => [
        'stage_dir' => '.wp-core-base/build/runtime',
        'manifest_mode' => 'strict',
        'validation_mode' => 'source-clean',
        'ownership_roots' => ['cms/plugins', 'cms/themes', 'cms/mu-plugins', 'cms/shared-assets'],
        'staged_kinds' => ['plugin', 'theme', 'mu-plugin-package', 'mu-plugin-file', 'runtime-file', 'runtime-directory'],
        'validated_kinds' => ['plugin', 'theme', 'mu-plugin-package', 'mu-plugin-file', 'runtime-file', 'runtime-directory'],
        'forbidden_paths' => [
            '.git',
            '.github',
            '.gitlab',
            '.circleci',
            '.wordpress-org',
            'node_modules',
            'docs',
            'doc',
            'tests',
            'test',
            '__tests__',
            'examples',
            'example',
            'demo',
            'screenshots',
        ],
        'forbidden_files' => [
            'README*',
            'CHANGELOG*',
            '.gitignore',
            '.gitattributes',
            'phpunit.xml*',
            'composer.json',
            'composer.lock',
            'package.json',
            'package-lock.json',
            'pnpm-lock.yaml',
            'yarn.lock',
        ],
        'allow_runtime_paths' => [],
        'strip_paths' => [],
        'strip_files' => [],
    ],
    'github' => [
        'api_base' => getenv('GITHUB_API_URL') ?: 'https://api.github.com',
    ],
    'automation' => [
        'base_branch' => null,
        'dry_run' => (bool) getenv('WPORG_UPDATE_DRY_RUN'),
        'managed_kinds' => ['plugin', 'theme'],
    ],
    'dependencies' => [
        [
            'name' => 'WooCommerce',
            'slug' => 'woocommerce',
            'kind' => 'plugin',
            'management' => 'managed',
            'source' => 'wordpress.org',
            'path' => 'cms/plugins/woocommerce',
            'main_file' => 'woocommerce.php',
            'version' => '10.6.1',
            'checksum' => 'sha256:...',
            'archive_subdir' => '',
            'extra_labels' => ['plugin:woocommerce'],
            'source_config' => [
                'github_repository' => null,
                'github_release_asset_pattern' => null,
                'github_token_env' => null,
            ],
            'policy' => [
                'class' => 'managed-upstream',
                'allow_runtime_paths' => [],
            ],
        ],
        [
            'name' => 'Example Private Plugin',
            'slug' => 'example-private-plugin',
            'kind' => 'plugin',
            'management' => 'managed',
            'source' => 'github-release',
            'path' => 'cms/plugins/example-private-plugin',
            'main_file' => 'example-private-plugin.php',
            'version' => '1.2.3',
            'checksum' => 'sha256:...',
            'archive_subdir' => '',
            'extra_labels' => ['plugin:example-private-plugin'],
            'source_config' => [
                'github_repository' => 'owner/private-plugin',
                'github_release_asset_pattern' => '*.zip',
                'github_token_env' => 'PRIVATE_PLUGIN_GITHUB_TOKEN',
            ],
            'policy' => [
                'class' => 'managed-private',
                'allow_runtime_paths' => [],
            ],
        ],
        [
            'name' => 'Project Theme',
            'slug' => 'project-theme',
            'kind' => 'theme',
            'management' => 'local',
            'source' => 'local',
            'path' => 'cms/themes/project-theme',
            'main_file' => 'style.css',
            'version' => '1.0.0',
            'checksum' => null,
            'archive_subdir' => '',
            'extra_labels' => ['theme:project-theme'],
            'source_config' => [
                'github_repository' => null,
                'github_release_asset_pattern' => null,
                'github_token_env' => null,
            ],
            'policy' => [
                'class' => 'local-owned',
                'allow_runtime_paths' => [],
                'strip_paths' => [],
                'strip_files' => ['README*', 'package.json'],
            ],
        ],
        [
            'name' => 'Project Bootstrap',
            'slug' => 'project-bootstrap',
            'kind' => 'mu-plugin-file',
            'management' => 'local',
            'source' => 'local',
            'path' => 'cms/mu-plugins/project-bootstrap.php',
            'version' => '1.0.0',
            'checksum' => null,
            'archive_subdir' => '',
            'extra_labels' => ['mu-plugin:project-bootstrap'],
            'source_config' => [
                'github_repository' => null,
                'github_release_asset_pattern' => null,
                'github_token_env' => null,
            ],
            'policy' => [
                'class' => 'local-owned',
                'allow_runtime_paths' => [],
                'strip_paths' => [],
                'strip_files' => [],
            ],
        ],
        [
            'name' => 'Shared Assets',
            'slug' => 'shared-assets',
            'kind' => 'runtime-directory',
            'management' => 'local',
            'source' => 'local',
            'path' => 'cms/shared-assets',
            'version' => null,
            'checksum' => null,
            'archive_subdir' => '',
            'extra_labels' => [],
            'source_config' => [
                'github_repository' => null,
                'github_release_asset_pattern' => null,
                'github_token_env' => null,
            ],
            'policy' => [
                'class' => 'local-owned',
                'allow_runtime_paths' => [],
                'strip_paths' => [],
                'strip_files' => [],
            ],
        ],
    ],
];
